id: P737DC500
initial_creation_type: input
source_metadata:
  title: Bodhisattvayogācāracatuḥśatakaṭīkā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Klaus Wille
  contribution to GRETIL: Klaus Wille
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:11:46.424672'
last_modified_at: '2022-03-09T15:11:46.424716'
